# 网站标题
title = "瞻鹤的博客"
# 网站部署的网址
baseURL = 'https://slni.github.io/'
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"
[menu]
[[menu.main]]
    identifier = "home"
    name = "主页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4
     [[menu.main]]
    identifier = "friend"
    name = "友链"
    url = "/friends/"
    weight = 5

[params.footer]
    enable = true
    copyright = true
    author = true
    since = "2024"
    gov = ""
    icp = ""
    license = ""
    [params.footer.powered]
      enable = true
      hugoLogo = true
      themeLogo = true
    [params.footer.siteTime]
      enable = false
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = ""
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0

# 主页配置
[params.home]
# FixIt 0.2.0 | 新增 RSS 文章数目
rss = 10
  # 主页个人信息
  [params.home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/images/avatar.jpg"
    # FixIt 0.2.17 | 新增 头像菜单链接的 identifier
    avatarMenu = ""
    # FixIt 0.2.7 | 更改 主页显示的网站标题（支持 HTML 格式）
    title = "仰天一笑，快意平生"
    # 主页显示的网站副标题
    subtitle = "学习——分享"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = false
    # FixIt 0.2.0 | 新增 免责声明（支持 HTML 格式）
    disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
  [markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/hugo-fixit/FixIt/issues/43)
    noClasses = false
[params]
  [params.author]
    name = "瞻鹤"
    email = "he-zhan@outlook.com"
    link = ""
    avatar = "/images/avatar.jpg"
  [params.page]
  # FixIt 0.2.18 | 新增 是否启用文章作者头像
    authorAvatar = true
  [params.page.library]
    [params.page.library.js]
      flyfish = "/js/flyfish.js"
[params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    placeholder = "搜索~"
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false
[params.tagcloud]
    enable = false
    min = 14
    max = 32
    peakCount = 10
    orderby = "name"
    [params.ibruce]
    enable = true
    enablePost = true
[params.githubCorner]
    enable = true
    permalink = "https://github.com/1006487432/1006487432.github.io"
    title = "View source on GitHub"
    position = "right"
[params.readingProgress]
    enable = true
    start = "left"
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"
[params.pace]
    enable = false
    color = "blue"
    theme = "minimal"
[params.page.comment]
      enable = true
    [params.page.comment.giscus]
        enable = true
        repo = "1006487432/1006487432.github.io"
        repoId = "R_kgDOKIFOrw"
        category = "Announcements"
        categoryId = "DIC_kwDOKIFOr84CgAVb"
        mapping = "pathname"
        origin = "https://giscus.app" # FixIt 0.3.7 | 新增 Or set it to your self-hosted domain
        strict = "0" # FixIt 0.2.18 | 新增
        term = ""
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top" # ["top", "bottom"]
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
[outputs]
  home = ["HTML", "RSS", "JSON"]